#!/bin/bash
# UPMS Backend - Quick Start Script
# This script demonstrates how to start the system

echo "=========================================="
echo "UPMS Backend - Quick Start Guide"
echo "=========================================="
echo ""

# Step 1: Start Docker Compose
echo "Step 1: Starting Docker Compose environment..."
echo "Command: docker-compose up -d"
echo ""

# Step 2: Wait for services
echo "Step 2: Waiting for services to start (30-45 seconds)..."
echo "Command: docker-compose logs -f"
echo ""

# Step 3: Verify services
echo "Step 3: Verify all services are running"
echo "Commands:"
echo "  curl http://localhost:8081/api/v1/auth/health"
echo "  curl http://localhost:8082/api/v1/procurement/health"
echo "  curl http://localhost:8083/api/v1/bidding/health"
echo "  curl http://localhost:8084/api/v1/evaluation/health"
echo ""

# Step 4: Access services
echo "Step 4: Access the services"
echo "=========================================="
echo "Swagger Documentation:"
echo "  Auth Service:         http://localhost:8081/swagger-ui.html"
echo "  Procurement Service:  http://localhost:8082/swagger-ui.html"
echo "  Bidding Service:      http://localhost:8083/swagger-ui.html"
echo "  Evaluation Service:   http://localhost:8084/swagger-ui.html"
echo ""
echo "Database Management:"
echo "  PgAdmin:              http://localhost:5050"
echo "  Email: admin@upms.local"
echo "  Password: admin"
echo ""

# Step 5: Test Login
echo "Step 5: Test authentication"
echo "Command: curl -X POST http://localhost:8081/api/v1/auth/login \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{\"username\":\"test@upms.local\",\"password\":\"password123\"}'"
echo ""

# Useful Commands
echo "=========================================="
echo "Useful Commands"
echo "=========================================="
echo ""
echo "View Logs:"
echo "  docker-compose logs -f"
echo "  docker-compose logs -f auth"
echo "  docker-compose logs -f procurement"
echo ""
echo "Stop Services:"
echo "  docker-compose down"
echo ""
echo "Remove Everything (including data):"
echo "  docker-compose down -v"
echo ""
echo "Rebuild Images:"
echo "  docker-compose build --no-cache"
echo ""
echo "Execute Command in Container:"
echo "  docker-compose exec auth bash"
echo "  docker-compose exec postgres-auth psql -U postgres"
echo ""

echo "=========================================="
echo "Next Steps"
echo "=========================================="
echo ""
echo "1. Review comprehensive documentation:"
echo "   - README.md - Quick overview"
echo "   - API_DOCUMENTATION.md - Complete API reference (500+ lines)"
echo "   - IMPLEMENTATION_SUMMARY.md - What's been created"
echo ""
echo "2. Explore the Swagger UIs to understand all available endpoints"
echo ""
echo "3. Start implementing business logic in service classes:"
echo "   - auth/src/main/java/com/v1/auth/service/"
echo "   - procurement/src/main/java/com/v1/procurement/service/"
echo "   - bidding/src/main/java/com/v1/bidding/service/"
echo "   - evaluation/src/main/java/com/v1/evaluation/service/"
echo ""
echo "4. Run the system: docker-compose up -d"
echo ""
echo "=========================================="
